pkgname=pastie

post_install() {
  gconfpkg --install $pkgname
  xdg-icon-resource forceupdate --theme ubuntu-mono-dark
  xdg-icon-resource forceupdate --theme ubuntu-mono-light
}

pre_upgrade() {
  pre_remove $1
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  gconfpkg --uninstall $pkgname
}

post_remove() {
  xdg-icon-resource forceupdate --theme ubuntu-mono-dark
  xdg-icon-resource forceupdate --theme ubuntu-mono-light
}
